name: Publish

on:
  workflow_dispatch:   # Allows manual trigger

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
        id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "^3.13"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          sudo apt install pipx
          pipx install poetry
          poetry install
          poetry build
          
      - name: upload release to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1